### ISSUE TITLE
google is not defined

### ISSUE THREAD

**Issue by mattbtay** [peledies/google-places#1]
Using the basic markup (supplied) I am seeing this error - 
Uncaught ReferenceError:
 google is not defined
initialize_place @ google-places.js:32
plugin.init @ google-places.js:22
$.googlePlaces @ google-places.js:108
(anonymous function) @ google-places.js:116
n.extend.each @ jquery-2.1.4.min.js:2
n.fn.n.each @ jquery-2.1.4.min.js:2
$.fn.googlePlaces @ google-places.js:114
(anonymous function) @ index.html:320

**Comment by peledies** [comment]
Hey Matt,

Ill take a look and see whats up.

**Comment by mattbtay** [comment]
Oh, don't worry about, it's Monday, and I didn't include the Google Api script. Working great. Nice work.

**Comment by peledies** [comment]
Glad to hear you got it working. I updated the Readme to include the google api script, and a few other minor fixes.
