### ISSUE TITLE
Namespace is not defined

### ISSUE THREAD

**Issue by nikolabadev** [peledies/google-places#15]
Hello, 
When I try your demo, this error message appears: https://prnt.sc/ha1sp9
Do you know what the problem is?

Cheers,

**Comment by mdeuerlein** [comment]
You have to define the namespace outside/before the `$.googlePlaces` but leave the `defaults =` inside the function. So the first lines should look like this:

    var namespace = 'googlePlaces';
    
    $.googlePlaces = function(element, options) {
    
        var defaults =    
    
            { placeId: 'xxx',
    ....

**Comment by nikolabadev** [comment]
works fine, thanks a lot!
Cheers,Nikola
    On Sunday, November 26, 2017, 3:29:13 PM GMT+1, Markus Deuerlein <notifications@github.com> wrote:  
 
 
You have to define the namespace outside/before the $.googlePlaces but leave the defaults = inside the function. So the first lines should look like this:
var namespace = 'googlePlaces';

$.googlePlaces = function(element, options) {

    var defaults =    

        { placeId: 'xxx',
....
