### ISSUE TITLE
Does not show recent reviews

### ISSUE THREAD

**Issue by Mrtn91** [peledies/google-places#17]
i have 3 reviews and doesnt return the latest, if i put 4 i see one more recent than if i put three, how can i change the order or display the most recent ones?

**Comment by affinityphoto** [comment]
I think I read that Google sends the top 5 most relevant reviews, not the most recent.

**Comment by peledies** [comment]
@affinityphoto is correct. that is a limitation of the google API.

see https://github.com/peledies/google-places/issues/5 for more details
