### ISSUE TITLE
No reviews on live site

### ISSUE THREAD

**Issue by anshul0430** [peledies/google-places#20]
http://rotarydiabetescentre.org/index.html

There is not reviews showing when i live the website,

**Comment by peledies** [comment]
perhaps you're viewing a cached version. they loaded fine as far as i can tell
![screen shot 2018-04-02 at 9 51 14 am](https://user-images.githubusercontent.com/1185267/38198613-8a10afbc-365b-11e8-8d6e-08567d77413b.png)

**Comment by anshul0430** [comment]
great. actually, i haven't inserted Goggle Api map key
