### ISSUE TITLE
Please ADD 'shorten_names: true' Feature

### ISSUE THREAD

**Issue by weilinzung** [peledies/google-places#26]
Please ADD 'shorten_names: true' Feature

https://github.com/peledies/google-places/pull/27

**Comment by weilinzung** [comment]
Please make a new release: https://github.com/peledies/google-places/releases, and update the demo page: http://peledies.github.io/google-places/ Otherwise, can't install the latest version.

@peledies

**Comment by peledies** [comment]
new tag has been created. I dot have time to work on this component at the moment, but if you modify the demo page and documentation, I will merge in the changes.

**Comment by weilinzung** [comment]
good, but on https://www.npmjs.com/package/google-places-data which still has the old tag `0.1.1`.

The 'demo' folder`index` already has the latest changes, but not sure where are http://peledies.github.io/google-places/ files hosted.

**Comment by peledies** [comment]
the github.io pages are on the `gh-pages` branch.

I just tried to publish an update to the npm package and im getting a `403`. I believe i set this up to work with bower and another contributor set up the npm parts. might have to have them publish.

**Comment by weilinzung** [comment]
Bower shouldn't worry about it. NPM package update, would you figure it out soon?

Demo page has updated with pull request: https://github.com/peledies/google-places/pull/28

**Comment by weilinzung** [comment]
@peledies @bpedroza @chedaroo any news on the npm package update?

**Comment by peledies** [comment]
I havent heard anything back from the owner of the npm account. I may just go ahead and set up a new npm package that I can control. 

this feature has been merged into master though

**Comment by weilinzung** [comment]
@peledies yes, you should!
