### ISSUE TITLE
Username not showing

### ISSUE THREAD

**Issue by katie-stormbox** [peledies/google-places#30]
`reviews[i].author_name` is no longer outputting username, instead of usernames all reviews show they are from "A Google User"

**Comment by martinbkaiser** [comment]
I tried fixing this for a couple hours yesterday with no luck. But it seems like it might be a bug in the Places API. Some Google issue tracker tickets are popping up now https://issuetracker.google.com/issues/113880410 

From Google Support:
"Thanks for reporting this issue. We have verified and logged it internally.  Please note that we cannot give you any timelines, but you can star the issue to get notifications."

**Comment by martinbkaiser** [comment]
Bug seems to be fixed now

**Comment by katie-stormbox** [comment]
Excellent, thanks for following up
