### ISSUE TITLE
Doesn't fetch last reviews ...

### ISSUE THREAD

**Issue by thugic** [peledies/google-places#5]
Hi.

I've set up all the params and it is working fine, but it's been a week it does not show the newest reviews... 
Eg: I had 2 reviews since 04 Sept 2016 but the last one the plugins displays is 31 Aug 2016 ...

(yes I deleted my browser cache :))

Thanks for your input :)

**Comment by peledies** [comment]
what configuration parameters are you using?

**Comment by thugic** [comment]
Here's the link to the page

[redacted]

**Comment by peledies** [comment]
It would appear that this is a limitation of the google maps api. It will only return 5. It is not immediately clear what it uses to select which reviews to return.

**Comment by jo-koda** [comment]
hello after all these years is still this the case? is it still a limitation?
