### ISSUE TITLE
Does not returns recent 

### ISSUE THREAD

**Issue by dixonem** [peledies/google-places#6]
Hi,

Thanks for your plugin. 

I have configured the plugin according to your documentation. It returns the reviews. But the problem is, returned reviews are not most recent ones. Also it doesn't give reviews more than 5.

Could you please guide me ?

**Comment by peledies** [comment]
It would appear that this is a limitation of the google maps api. It will only return 5. It is not immediately clear what it uses to select which reviews to return.
