### ISSUE TITLE
I downloaded the demo and nothing happens

### ISSUE THREAD

**Issue by uglyeoin** [peledies/google-places#8]
When I try the demo page it just shows static text and no reviews.  Is there something I have to do to get the demo working?

**Comment by peledies** [comment]
can you provide more information. Are you referring to the demos in the documentation here -> http://peledies.github.io/google-places/fade_demo.html

**Comment by uglyeoin** [comment]
No when I download the zip file and then open the demos they don't work out of the box.  I assume it means I need to do something but I can't easily spot what it is I need to do.

**Comment by peledies** [comment]
The plugin was primarily intended to be installed via a package manager `npm` or `bower`and sourced in your website as per the instructions in the `readme`. I have updated the demo index.html so that it will source them from a CDN so the demo should work out of the box.

**Comment by uglyeoin** [comment]
Great thanks!

**Comment by uglyeoin** [comment]
What license is it under?  Can I use it on a production site?
