### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by DanielSokil** [peledies/google-places#9]
Does this plugin require an API key from google places ?

**Comment by DanielSokil** [comment]
![screenshot_059](https://user-images.githubusercontent.com/24403355/28045474-50939668-65ab-11e7-8d5b-0e8e43043e8c.png)

**Comment by mdeuerlein** [comment]
Try calling the maps.api like this:

`https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&v=3.exp&libraries=places`

and also remove `&signed_in=true` because it's [deprecated](https://developers.google.com/maps/documentation/javascript/error-messages#signed-in-not-supported)
